### ISSUE TITLE
еще проблемы

### ISSUE THREAD

**Issue by kirillgenets** [viktorevstigneev/Expense_Tracker#3]
https://github.com/viktorevstigneev/Expense_Tracker/blob/0f1016dc2b43b0081c1c9a148f0f55b6ca0cc287/js/main.js#L11-L14
1. такие переменные лучше объединить в объект
2. переменные без значения не инициализируются, как ты сделал на 13 строчке - это плохо
3. i выкинуть, можно 100% без нее

**Comment by viktorevstigneev** [comment]
такие переменные лучше объединить в объект 
не совсем понял какие именно переменные

**Comment by kirillgenets** [comment]
Ну вообще по сути score я не догнал зачем тебе, а transactions я не пытался понять, что это, поэтом пока не объединяй
