### ISSUE TITLE
innerHTML

### ISSUE THREAD

**Issue by kirillgenets** [viktorevstigneev/Expense_Tracker#6]
https://github.com/viktorevstigneev/Expense_Tracker/blob/0f1016dc2b43b0081c1c9a148f0f55b6ca0cc287/js/main.js#L22
забудь про innerHTML - это небезопасно!
textContent юзай https://developer.mozilla.org/ru/docs/Web/API/Node/textContent
и еще - используй ES6 с шаблонными строками. если не знаешь, что это такое - гугли

**Comment by viktorevstigneev** [comment]
я понял,только интересно почему это небезопасно?

**Comment by kirillgenets** [comment]
Потому что в innerHTML можно вставить тег script, код в котором изи выполнится и ты сам понимаешь, что разрешать пользователю это делать - пиздец
